crud_ajax/config/routes.rb
Rails.application.routes.draw do
  
  # Dapatin delete method melalui ajax
  resources :articles do
    get "delete"
    collection { post :import }
  end 

  # ROUTE STANDARD

  # get 'articles/edit', to: "articles#edit", as: :articles
  # ------------------------------------------------------

  # get "sign_up" => "users#new", :as => "sign_up"
  # get "login" => "session#new", :as => "login"
  resources :users
  resources :sessions

  # RESTFULL ROUTE
  root :to => "articles#index" 
  resources :articles

  resources :comments
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

crud_ajax/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crud_ajax/app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
						length: { minimum: 5 }
	validates :content, presence: true,
						length: { minimum: 10 }
	validates :status, presence: true

	scope :status_active, -> {where(status: 'active')}
	default_scope {where(status: 'active')}

	# has_many :comments, required: false  

	# def self.search(search)
	# 	if search
	# 		where('title LIKE ?', "%#{search}%")
	# 	else	
	# 		Article.all
	# 	end
	# end

	
end

crud_ajax/app/models/comment.rb
class Comment < ApplicationRecord
	before_create :default_status
	belongs_to :articles, required: false
	# belongs_to :user
	# validates :content, presence: true, length: {minimum: 10}

	def default_status
		self.status = "not-active"
	end

end

crud_ajax/app/models/user.rb
class User < ApplicationRecord
	include Humanizer
	require_human_on :create

	before_create :add_activation_token
	def add_activation_token
		self.activation_token = SecureRandom.urlsafe_base64
		self.activation_status = "not activated"
		# logika jika mau langsung login  =>  self.activation_status = "activated"
	end

	attr_accessor :password
	before_save :add_salt_and_hash

	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, on: :create,
		length: { minimum: 5},
		confirmation: true

	

	def add_salt_and_hash
		unless password.blank?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end	
	end
end

crud_ajax/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :check_current_user

  def current_user
  	current_user ||= User.where("id = ?", session[:user]).first
  end

  def check_current_user
  	if current_user.blank?
  		flash[:error] = "Please Login for Full Access"
  		redirect_to new_session_url
  	else
  		current_user
  	end
  end
end

crud_ajax/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# layout "articles"
  # instanisasi class harus sesuai nama kelas {tapi harus sama : article}
  
    # before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]

  # helper_method :sort_column, :sort_direction
  
  def index
    # @article = Article.all
    @article = Article.page(params[:page]).per(5)
    # render 'index'
    # @articles = Article.order(sort_column+ ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
    # @articles = Article.search(params[:search])
    # respond_to do |format|
    #   format.js{
    #     @article = Article.where("title like ? or content like ?", "%#{params[:search]}%", "%#{params[:search]}%").order("#{params[:column]} #{params[:direction]}")
    #   }
    # end
  end

  def new
    @article = Article.new
    @comment = Comment.new
  	
  end

   def edit
    @article = Article.find_by_id(params[:id])
  end

  def create
    @article = Article.new(params_artikel)
    if @article.save
    flash[:notice] = "Success Add Rows"
  else
    flash[:notice] = "Error Add Rows"
  end
  end

  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new

  end

  def delete 
    @article = Article.find_by_id(params[:article_id])
  end



  def update
    @article = Article.find_by_id(params[:id])
    if @article.update(params_artikel)
      flash[:notice] = "Success Update Rows"
      redirect_to action: 'index'
    else
      flash[:notice] = "Error Update Rows"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])

    if @article.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to action: 'index'
    else
      flash[:error] = "fails delete a records"
      redirect_to action: 'index'
    end

  end

  private
   def params_artikel
    params.require(:article).permit(:title, :content, :status)
  end  

 

  def list
  	  @artikel = Article.all
  end

  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

end

crud_ajax/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
  	  @comment = Comment.new(params_comment)
      respond_to do |format|
        if @comment.save
          format.js {@comments = Article.find_by_id(params[:comment][:article_id])}
          redirect_to root_url 
        else
          format.js {@article = Article.find_by_id(params[:comment][:article_id])}
        end
      end
  end

  private
    def params_comment
      params.require(:comment).permit(:article_id, :content)

    end

  def index
  end

  def new
  end

  def edit
  end
end

crud_ajax/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def edit
		user = User.find_by_activation_token(params[:id])
		if user.try(:update, {activation_token: "", activation_status: "active"})
			flash[:notice] = "Your account has active"
			redirect_to root_url
		else
			flash[:notice] = "Welcome to Rails 5"
			redirect_to root_url

		end

	end

	def create
		username = params[:username]
		password = params[:password]
		user = User.where("username =? ", username).first
		user_password = BCrypt::Engine.hash_secret(password, user.password_salt) unless user.blank?
		if !user_password.blank? and user.password_hash.eql? user_password
			session[:user] = user.id
			flash[:notice] = "Welcome #{user.username}"
			redirect_to root_url
		else
			flash[:error] = "Your data not valid"
			render "new"
		end		

	end

	def destroy
		session[:user] = nil
		flash[:notice] = "Anda Berhasil Logout"
		redirect_to root_url
	end
end

crud_ajax/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@user = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params_user)
  	if @user.save
  		begin
  		ConfirmationMailer.confirm_email("#{@user.email}", @user.activation_token).deliver
  	rescue
  		flash[:notice] = "activation instruction fails send to your email"
  		end
  		flash[:notice] = "activation instruction has send to #{@user.email}"
  		redirect_to root_url
  	else
  		flash[:error] = "Data Not Valid"
  		render "new"
  	end
  end

  def edit
  end

  private 
  def params_user
  		params.require(:user).permit(:username, :email, :password, :humanizer_answer, :humanizer_question_id)
end
end

crud_ajax/app/helpers/application_helper.rb
module ApplicationHelper
end

crud_ajax/app/views/articles/_article.html.erb
<tr>
	<td><%= article.title.titleize %></td>
	<td><%= truncate(article.content, :length => 50, :separator => ' ') %></td>
</tr>

crud_ajax/app/views/articles/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @article, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        
        <div class="form-group">
          <%= f.label :title, class:"control-label" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :content, class: "control-label" %>
          <%= f.text_area :content, cols: 20, rows: 10 , class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :status %>
            <%= f.radio_button :status, "active" , :checked => true  %>
            <%= f.label :article_status, 'active' %>
            <%= f.radio_button :status, "off"  %>
            <%= f.label :article_status, 'off' %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

crud_ajax/app/views/articles/_new.html.erb
<%= render "form" %>

crud_ajax/app/views/articles/_save.js.erb
  $("#article-modal").modal("hide")

crud_ajax/app/views/articles/articles.html.erb
<% content_for :list do %>
 This is the content for head
<% end %>

<h1>LIST</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
      <td></td>
    </tr>
  </thead>

  <tbody>
    <% @artikel.each do |article| %>
      <tr>
        <td><%= article.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

crud_ajax/app/views/articles/create.js.erb
<%= render "save" %>

crud_ajax/app/views/articles/destroy.js.erb
<%= render "save" %>

crud_ajax/app/views/articles/edit.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      <li class="nav-item"><%= link_to 'User', sign_up_path, class: 'btn btn-lg btn-info' %></li>
      
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Edit Data Artikel</h5>
                <%= form_for @article do |f| %>
                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: 'form-control' %>
                 
                  
                </div>
                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  
                  
                </div>
                <div class="form-group">
                  <%= f.label :status %>
                  <%= f.radio_button :status, "active" %>
                  <%= label :artikel_status, 'active' %>
                  <%= f.radio_button :status, "non-active", :checked => true %>
                  <%= label :artikel_status, 'off' %>
                </div>
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

                <%= link_to 'back', articles_path, class: 'btn btn-md btn-info'%>
               
        </div>
      </div>
    </section>
  </div>
</div>






  

crud_ajax/app/views/articles/edit.js.erb
$("#article-modal").html("<%= escape_javascript(render 'edit') %>")
$("#article-modal").modal("show")

crud_ajax/app/views/articles/index.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, remote: true,  class: 'btn btn-lg btn-warning' %></li>
			
			
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      <!-- END OF CONTENT -->

					 <h2>Selamat Datang</h2>
					 

				      <div class="jumbotron">
				      	<h1 class="display-4">Hello, world!</h1>
						<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
						<hr class="my-4">
						<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
						<p class="lead">
						<a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
						</p>
				      </div>

					

				      
				      <!-- Data Artikel -->
				      <table class="table table-bordered table-striped text-center" >
				      	<thead>

				      	</thead>
				      	<tbody class="article-index">
				      		<%= render "index" %>
				      	</tbody>
				      </table>
				      
				      	
				     
				</div>
			</div>
		</section>
	</div>
</div>

<%= javascript_include_tag 'custom' %>

<div id="article-modal" class="modal fade"></div>
	
  
</body>
</html>

crud_ajax/app/views/articles/index.js.erb
$('#article-index').html("<%= j(render @articles) %>");
$('#direction').prop("checked",!$("#direction").prop("checked"));

crud_ajax/app/views/articles/new.js.erb
$("#article-modal").html("<%= escape_javascript(render 'new') %>")
$("#article-modal").modal("show")

crud_ajax/app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>List Data</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
			<li class="nav-item"><%= link_to 'User', sign_up_path, class: 'btn btn-lg btn-info' %></li>
			
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      <!-- END OF CONTENT -->

					 <h3><%= @article.title %></h3>
					 <p><%= @article.content %></p>

					 	<section class="section comments mb-5">
							<div class="">
								<h2 class="subtitle is-5"><strong><%= @article.comments.count %></strong> Comments</h2>
								<div id="list-comments">
									<%= render 'comments/comments'%>
								</div>
								<div class="comment-form">
									<hr />
									<h3 class="subtitle is-3">Leave a reply</h3>
									<div id="form-comment">
								 		<%= render 'comments/form' %>
									</div>
								</div>
							</div>
						</section>

					 <p><%= link_to 'back', articles_path, class: 'btn btn-md btn-info'%></p> 	
				     
				</div>
			</div>
		</section>
	</div>
</div>
	
  
</body>
</html>

crud_ajax/app/views/articles/update.js.erb
<%= render "save" %>

crud_ajax/app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
	<p>
		
		<br/>
		<%= comment.content %>
	</p>

<% end %>

crud_ajax/app/views/comments/_form.html.erb
<%= form_for @comment, url: comments_path, remote: true  do |f| %>
	
	<%= f.hidden_field :article_id, value: @article.id %>
	
	<br />
	<%= f.label :content %>
	<%= f.text_area :content, cols: 20, rows: 10 , class: 'form-control'%>
	<br />
	<%= f.submit :submit , class: 'btn btn-primary' %>
<% end %>

crud_ajax/app/views/comments/create.js.erb
<% if @comment.errors.present? %>
$("#form-comment").html(" <%= j( render 'form' ) %>");
$($(".field_with_errors")[0]).append("<p class = 'message'> <%= escape_javascript( @comment.errors[:content].first ) %></p>");
<% else %>
$("#list-comments").html(" <%= j( render 'comments' ) %>");
$("#comment_content").val('');
$("div.field_with_errors p.message").remove();
<% end %>

crud_ajax/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

crud_ajax/app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

crud_ajax/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

crud_ajax/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Latihan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'main' %>

  </head>
  <body>
    <%= yield %>

  </body>
</html>

crud_ajax/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

crud_ajax/app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>List Data</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
			<li class="nav-item"><%= link_to 'User', new_user_path, class: 'btn btn-lg btn-info' %></li>
			
			
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      <!-- END OF CONTENT -->

					 <h2>Selamat Datang</h2>
				      

				      <!-- Data Artikel -->
				      <table class="table table-striped">
				      	<thead>
				      		<tr>
				      			<th>Username</th>
				      			<th>Email</th>
				      			<th>Password</th>
				      			<th>Action</th>
				      		</tr>
				      	</thead>
				      	<tbody>
				      		<% @user.each do |user| %>
				      		<tr>
				      			<td><%= article.username %></td>
				      			<td><%= article.email %></td>
				      			<td><%= article.password %></td>
				      			<td></td>
	   				       <% end %>
				      		</tr>
				      	</tbody>
				      </table>
				      
				      	
				     
				</div>
			</div>
		</section>
	</div>
</div>
	
  
</body>
</html>

crud_ajax/app/views/users/new.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      <li class="nav-item"><%= link_to 'User', new_user_path, class: 'btn btn-lg btn-info' %></li>
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Tambah Data Users</h5>
                <%= form_for (@user) do |f| %>
                <div class="form-group">
                  <%= f.label :username %>
                  <%= f.text_field :username, class: 'form-control' %>
                  <%= @user.errors[:username].first unless @user.errors[:username].blank? %>

                  
                </div>
                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.text_field :email, class: 'form-control' %>
                  <%= @user.errors[:email].first unless @user.errors[:email].blank? %>
                  
                </div>

                <div class="form-group">
                  <%= f.label :password %>
                  <%= f.password_field :password, class: 'form-control' %>
                  <%= @user.errors[:password].first unless @user.errors[:password].blank? %>
                </div>

                <div class="form-group">
                  <%= f.label :humanizer_answer, @user.humanizer_question %>
                <%= f.text_field :humanizer_answer, class: 'form-control' %>
                <%= f.hidden_field :humanizer_question_id %>  
                </div>
                
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

        </div>
      </div>
    </section>
  </div>
</div>






  